Repository eab-agency/advance.appily.com, pull requests merged in 2025-02, with the labels that each got.

#54 Bugfix resolve conflicts
  .github/workflows/feature-branch.yaml
  src/app/(home)/(pages)/blog/[category]/[post]/page.tsx
  src/app/graphql/index.ts
  src/app/graphql/posts.ts
Labels: Review effort [1-5]: 2

#57 🔧 fix(page.tsx): update metadata title and description for Master's D…
  src/app/lps/business/page.tsx
  src/app/lps/mba/page.tsx
  src/app/lps/medical/page.tsx
  src/app/lps/nursing/page.tsx
Labels: Review effort [1-5]: 2

#59 Update README.md
  README.md
Labels: Review effort [1-5]: 1

#61 Bugfix blog posts published date
  src/app/(home)/(pages)/blog/page.tsx
  src/components/Blog/BlogTab/index.tsx
  src/components/Blog/PostDateDisplay.tsx
  src/data/careers-adc.json
Labels: Review effort [1-5]: 2

#63 Bugfix sass function deprecated
  package.json
  pnpm-lock.yaml
  src/app/lps/business/page.tsx
  src/app/lps/healthcare/page.tsx
  src/app/lps/mba/page.tsx
  src/app/lps/medical/page.tsx
  src/app/lps/nursing/page.tsx
  src/styles/global/tokens/_themes.scss
Labels: Review effort [1-5]: 2

#65 Delete stage on branch deletion
  .github/workflows/branch-deleted.yaml
  .github/workflows/clear-preview.yaml
Labels: Review effort [1-5]: 2

#66 update readme
  README.md
Labels: Review effort [1-5]: 1

#71 Bugfix nursing lps h1 and CTA
  src/app/lps/nursing/page.tsx
Labels: Review effort 1/5

#73 🔨 refactor(page.tsx): remove StickyCta component from art-and-design,…
  src/app/(home)/degree-completion/plan/(results)/art-and-design/page.tsx
  src/app/(home)/degree-completion/plan/(results)/business/page.tsx
  src/app/(home)/degree-completion/plan/(results)/criminal-justice/page.tsx
  src/app/(home)/degree-completion/plan/(results)/education/page.tsx
  src/app/(home)/degree-completion/plan/(results)/healthcare/page.tsx
  src/app/(home)/degree-completion/plan/(results)/other/page.tsx
  src/app/(home)/degree-completion/plan/(results)/stem/page.tsx
  src/app/(home)/degree-completion/results/page.tsx
  src/app/lps/layout.tsx
Labels: Review effort 2/5
